# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Con Cu Tùng Anh"

# URL
url: "hoangphatdeptrai.github.io/concuduongtunganh"
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About me"
    href:           "/about"
  - name:           "My stuff"
    href:           "/my-stuff"
  - name:           "Lifetalk"
    href:           "/lifetalk"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
