# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Tùng Anh"

# URL
url: "duongtunganh.space"
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Home"
    href:           "//duongtunganh.space"
  - name:           "About"
    href:           "/about"
  - name:           "Tools"
    href:           "/tech"
  - name:           "Programming"
    href:           "/dev"
  - name:           "Graphics"
    href:           "/graphics"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
