# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Duong Tung Anh"

# URL
url: "duongtunganh.github.io"
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Giới thiệu"
    href:           "/about"
  - name:           "Lập trình"
    href:           "/dev"
  - name:           "Đồ hoạ"
    href:           "/graphics"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
